name: Markdown with PlantUML to PDF and HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get -y install pandoc

    - name: Install PlantUML
      run: |
        sudo apt-get -y install default-jre  # 安装 Java 运行环境
        sudo apt-get -y install plantuml

    - name: Convert PlantUML to Images
      run: |
        find . -type f -name "*.md" -exec sh -c 'pandoc -s -t json "$1" | pandoc -f json -t markdown-smart' sh {} \;

    - name: Convert Markdown to PDF
      run: |
        pandoc input.md -o output.pdf

    - name: Convert Markdown to HTML
      run: |
        pandoc input.md -o output.html

    - name: Upload PDF and HTML artifacts
      uses: actions/upload-artifact@v2
      with:
        name: converted-docs
        path: |
          output.pdf
          output.html
